const CardStyle = {
  card: {
    width: "100%",
    bgcolor: "primary.main",
    boxShadow: "0 0.125rem 0.25rem rgba(0,0,0,0.16);",
    cursor: "pointer",
  },
  car_box_one: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "space-between",
  },
  card_content: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "space-between",
  },
  card_box_two: {
    display: "flex",
    flexDirection: "column",
    alignItems: "felx-start",
    padding: "1.5rem",
  },
  card_impact: {
    color: "custom.midnight",
    display: { xs: "none", lg: "inline-block" },
    backgroundColor: "custom.gray_pill_background",
    borderRadius: "4px",
    textTransform: "uppercase",
    padding: "0.25rem 0.5rem",
    letterSpacing: "0.05rem",
    fontWeight: "fontWeight.regular",
    fontSize: "font.font_size_mediumtiny",
    lineHeight: "1.5",
    margin: "0 1rem 1rem 0",
  },
  card_box_three: {
    display: "flex",
    flexDirection: "column",
    alignItems: "felx-start",
    textAlign: "left",
  },
  card_header: {
    color: "custom.midnight",
    letterSpacing: "0.0063rem",
    fontWeight: "fontWeight.bold",
    fontSixe: "font.font_size_mediumsmall",
    lineHeight: "1.5",
  },
  card_body: {
    color: "custom.midnight",
    letterSpacing: "0.0063rem",
    fontWeight: "fontWeight.regular",
    fontSize: "font.font_size_mediummini",
    lineHeight: "1.5",
  },
  card_lg_impact: {
    color: "custom.midnight",
    display: { xs: "inline-block", lg: "none" },
    backgroundColor: "custom.gray_pill_background",
    borderRadius: "0.25rem",
    padding: "0.25rem 0.5rem",
    textTransform: "uppercase",
    letterSpacing: "0.05rem",
    fontWeight: "fontWeight.regular",
    fontSize: "font.font_size_mediumtiny",
    lineHeight: "2",
    textAlign: "center",
    marginTop: "1rem",
  },
};
export default CardStyle;
